import styles from '../styles/Default.module.css';
import { useRouter } from 'next/router';
import { Counter } from '../modules/Counter';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { useEffect, useState } from 'react';

export default function User() {
  const router = useRouter();
  const { pid } = router.query;
  const [cal, setCal] = useState<JSX.Element | null>(null);
  useEffect(() => {
    if (!cal)
      import('../modules/Calendar').then((mod) => {
        console.log('Loaded');
        console.log(mod.Calendar);

        setCal(mod.Calendar);
      });
  }, [cal]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Page {pid}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Page : {pid}</div>
      <div>calendar : {typeof cal}</div>
      <Counter />
      {cal ? <cal /> : null}
    </div>
  );
}
