import styles from '../styles/Default.module.css';
import { useRouter } from 'next/router';
import { Counter } from '../modules/Counter';
import Head from 'next/head';
import { db } from './api/firebase';
import { doc } from 'firebase/firestore';
import { AddCredits } from '../modules/AddCredits';
import { Calendar } from '../modules/Calendar';

export default function User() {
  const router = useRouter();
  const pid = router.query.pid as string;
  if (!pid) return <main className={styles.main}>Loading</main>;

  const userRef = doc(db, 'users', pid);

  return (
    <div className={styles.container}>
      <Head>
        <title>Page {pid}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Counter userRef={userRef} />
        <AddCredits userRef={userRef} />
        <Calendar />
      </main>
    </div>
  );
}
