import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { collection, addDoc, getDocs, doc, getDoc, onSnapshot, runTransaction } from 'firebase/firestore';
import { db } from './api/firebase';
import { useEffect, useState } from 'react';

const dataRef = doc(db, 'nikki', 'data');

async function addCredits(amount: number) {
  try {
    await runTransaction(db, async (transaction) => {
      const sfDoc = await transaction.get(dataRef);
      if (!sfDoc.exists()) {
        throw 'Document does not exist!';
      }

      const newCredits = sfDoc.data().credits + amount;
      transaction.update(dataRef, { credits: newCredits });
    });
    console.log('Transaction successfully committed!');
  } catch (e) {
    console.log('Transaction failed: ', e);
  }
}

const Home: NextPage = () => {
  const [credits, setCredits] = useState(0);
  useEffect(() => {
    const unsub = onSnapshot(dataRef, (doc) => {
      setCredits(doc.data()?.credits);
    });
    async function getCredits() {
      const dataSnap = await getDoc(dataRef);
      if (dataSnap.exists()) return dataSnap.data().credits;
      else return 0;
    }
    getCredits().then((cred) => {
      setCredits(cred);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Credits : {credits}</h1>
        <div>
          <button
            className={styles.card}
            onClick={() => {
              addCredits(-10);
            }}
          >
            -
          </button>
          <button
            className={styles.card}
            onClick={() => {
              addCredits(10);
            }}
          >
            +
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
